print("name: Jovel Varghese Jose")
print("email: jovelvarghesejose718@gmail.com")
print("slack username@biostack: jovel@transcriptomics")
print("twitter handle: gravityboyjovel")
print("hamming distance: 5")
